/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type ComposerScrollContainer = {
  _type: "composerScrollContainer";
  title?: string;
  items?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "composer";
  }>;
  showScrollbar?: boolean;
};

export type EventScrollContainer = {
  _type: "eventScrollContainer";
  title?: string;
  items?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "event";
  }>;
  showScrollbar?: boolean;
  showDate?: boolean;
  showTime?: boolean;
  showVenue?: boolean;
  showArtists?: boolean;
  sortBy?: "date-asc" | "date-desc" | "title-asc" | "manual";
};

export type ArtistScrollContainer = {
  _type: "artistScrollContainer";
  title?: string;
  items?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "artist";
  }>;
  showScrollbar?: boolean;
};

export type ContentScrollContainer = {
  _type: "contentScrollContainer";
  title?: string;
  items?: Array<{
    _key: string;
  } & ImageComponent | {
    _key: string;
  } & VideoComponent | {
    _key: string;
  } & QuoteComponent | {
    _key: string;
  } & PortableTextBlock>;
  showScrollbar?: boolean;
};

export type ThreeColumnLayout = {
  _type: "threeColumnLayout";
  title?: string;
  column1?: Array<{
    _key: string;
  } & ImageComponent | {
    _key: string;
  } & VideoComponent | {
    _key: string;
  } & QuoteComponent>;
  column2?: Array<{
    _key: string;
  } & ImageComponent | {
    _key: string;
  } & VideoComponent | {
    _key: string;
  } & QuoteComponent>;
  column3?: Array<{
    _key: string;
  } & ImageComponent | {
    _key: string;
  } & VideoComponent | {
    _key: string;
  } & QuoteComponent>;
  aspectRatio?: "4:5" | "9:16" | "1:1";
};

export type TwoColumnLayout = {
  _type: "twoColumnLayout";
  title?: string;
  leftColumn?: Array<{
    _key: string;
  } & ImageComponent | {
    _key: string;
  } & VideoComponent | {
    _key: string;
  } & SpotifyComponent | {
    _key: string;
  } & QuoteComponent | {
    _key: string;
  } & PortableTextBlock | {
    _key: string;
  } & HeadingComponent>;
  rightColumn?: Array<{
    _key: string;
  } & ImageComponent | {
    _key: string;
  } & VideoComponent | {
    _key: string;
  } & SpotifyComponent | {
    _key: string;
  } & QuoteComponent | {
    _key: string;
  } & PortableTextBlock | {
    _key: string;
  } & HeadingComponent>;
  reverseOnMobile?: boolean;
  aspectRatio?: "4:5" | "9:16" | "1:1";
};

export type GridComponent = {
  _type: "gridComponent";
  title?: string;
  columns?: "2" | "3";
  items?: Array<{
    _key: string;
  } & ImageComponent | {
    _key: string;
  } & VideoComponent | {
    _key: string;
  } & QuoteComponent | {
    _key: string;
  } & SpotifyComponent>;
  aspectRatio?: "4:5" | "1:1";
  gap?: "small" | "medium" | "large";
};

export type PageBuilder = Array<{
  _key: string;
} & HeadingComponent | {
  _key: string;
} & PortableTextBlock | {
  _key: string;
} & QuoteComponent | {
  _key: string;
} & MarqueeComponent | {
  _key: string;
} & ImageComponent | {
  _key: string;
} & VideoComponent | {
  _key: string;
} & SpotifyComponent | {
  _key: string;
} & GridComponent | {
  _key: string;
} & TwoColumnLayout | {
  _key: string;
} & ThreeColumnLayout | {
  _key: string;
} & ButtonComponent | {
  _key: string;
} & LinkComponent | {
  _key: string;
} & AccordionComponent | {
  _key: string;
} & CountdownComponent | {
  _key: string;
} & ContentScrollContainer | {
  _key: string;
} & ArtistScrollContainer | {
  _key: string;
} & EventScrollContainer | {
  _key: string;
} & ComposerScrollContainer>;

export type CountdownComponent = {
  _type: "countdownComponent";
  title?: string;
  targetDate?: string;
  style?: "large" | "compact" | "minimal";
  completedMessage?: string;
  hideWhenComplete?: boolean;
};

export type AccordionComponent = {
  _type: "accordionComponent";
  title?: string;
  description?: string;
  panels?: Array<{
    title?: string;
    content?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    } | {
      _key: string;
    } & ImageComponent | {
      _key: string;
    } & VideoComponent | {
      _key: string;
    } & ButtonComponent | {
      _key: string;
    } & Title | {
      _key: string;
    } & QuoteComponent | {
      _key: string;
    } & HeadingComponent>;
    _type: "accordionPanel";
    _key: string;
  }>;
  accessibility?: {
    ariaLabel?: string;
    ariaDescribedBy?: string;
  };
};

export type LinkComponent = {
  _type: "linkComponent";
  links?: Array<{
    linkType?: "external" | "internal";
    text?: string;
    url?: string;
    internalLink?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "homepage";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "programPage";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "artistPage";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "articlePage";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "page";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "event";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "artist";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "article";
    };
    description?: string;
    openInNewTab?: boolean;
    _type: "link";
    _key: string;
  }>;
};

export type ButtonComponent = {
  _type: "buttonComponent";
  text?: string;
  url?: string;
  style?: "primary" | "secondary" | "outline";
  fullWidth?: boolean;
  openInNewTab?: boolean;
};

export type SpotifyComponent = {
  _type: "spotifyComponent";
  spotifyUrl?: string;
};

export type VideoComponent = {
  _type: "videoComponent";
  videoType?: "sanity" | "youtube" | "vimeo" | "external";
  video?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  youtubeUrl?: string;
  vimeoUrl?: string;
  externalUrl?: string;
  aspectRatio?: "1:1" | "4:5" | "9:16" | "16:9";
  title?: string;
  description?: string;
  autoplay?: boolean;
  muted?: boolean;
  controls?: boolean;
  loop?: boolean;
};

export type ImageComponent = {
  _type: "imageComponent";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  credit?: string;
  alt?: string;
  caption?: string;
  aspectRatio?: "1:1" | "4:5" | "9:16" | "16:9";
};

export type PortableTextBlock = {
  _type: "portableTextBlock";
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
};

export type PortableText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    openInNewTab?: boolean;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
  _type: "image";
  _key: string;
}>;

export type HeadingComponent = {
  _type: "headingComponent";
  level?: "h2" | "h3" | "h4";
  text?: string;
  id?: Slug;
};

export type MarqueeComponent = {
  _type: "marqueeComponent";
  text?: string;
};

export type QuoteComponent = {
  _type: "quoteComponent";
  quote?: string;
  author?: string;
  source?: string;
  cite?: string;
};

export type Title = {
  _type: "title";
  mainTitle?: string;
  subtitle?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  organizationName_no?: string;
  description_no?: string;
  newsletterTitle_no?: string;
  organizationName_en?: string;
  description_en?: string;
  newsletterTitle_en?: string;
  startDate?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "eventDate";
  };
  endDate?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "eventDate";
  };
  menuItems?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "homepage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "programPage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "artistPage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "articlePage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  }>;
  logos?: Array<{
    name?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    description?: string;
    _key: string;
  }>;
  favicon?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  email?: string;
  phone?: string;
  address?: string;
  linkUrl?: string;
  openInNewTab?: boolean;
  socialMedia?: Array<{
    name?: string;
    url?: string;
    _key: string;
  }>;
  sponsors?: Array<{
    name?: string;
    logo?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    url?: string;
    _key: string;
  }>;
  newsletterUrl?: string;
  featuredImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  featuredImageCredit_no?: string;
  featuredImageCredit_en?: string;
  featuredImageAlt_no?: string;
  featuredImageAlt_en?: string;
  defaultSeo?: Seo;
};

export type Composer = {
  _id: string;
  _type: "composer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description_no?: PortableText;
  description_en?: PortableText;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imageCredit_no?: string;
  imageCredit_en?: string;
  imageAlt_no?: string;
  imageAlt_en?: string;
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  adminTitle?: string;
  headerLinks_no?: Array<{
    linkType?: "external" | "internal";
    text?: string;
    description?: string;
    url?: string;
    internalLink?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "programPage";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "artistPage";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "articlePage";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "page";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "event";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "artist";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "article";
    };
    _type: "headerLink";
    _key: string;
  }>;
  content_no?: PageBuilder;
  headerLinks_en?: Array<{
    linkType?: "external" | "internal";
    text?: string;
    description?: string;
    url?: string;
    internalLink?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "programPage";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "artistPage";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "articlePage";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "page";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "event";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "artist";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "article";
    };
    _type: "headerLinkEn";
    _key: string;
  }>;
  content_en?: PageBuilder;
  homePageType?: "default" | "scheduled";
  scheduledPeriod?: {
    startDate?: string;
    endDate?: string;
  };
  seo?: Seo;
};

export type ProgramPage = {
  _id: string;
  _type: "programPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title_no?: string;
  slug_no?: Slug;
  excerpt_no?: string;
  content_no?: PageBuilder;
  title_en?: string;
  slug_en?: Slug;
  excerpt_en?: string;
  content_en?: PageBuilder;
  selectedEvents?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "event";
  }>;
};

export type ArtistPage = {
  _id: string;
  _type: "artistPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title_no?: string;
  slug_no?: Slug;
  excerpt_no?: string;
  content_no?: PageBuilder;
  title_en?: string;
  slug_en?: Slug;
  excerpt_en?: string;
  content_en?: PageBuilder;
  selectedArtists?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "artist";
  }>;
};

export type ArticlePage = {
  _id: string;
  _type: "articlePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title_no?: string;
  slug_no?: Slug;
  excerpt_no?: string;
  content_no?: PageBuilder;
  title_en?: string;
  slug_en?: Slug;
  excerpt_en?: string;
  content_en?: PageBuilder;
  selectedArticles?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "article";
  }>;
  seo?: Seo;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title_no?: string;
  slug_no?: Slug;
  content_no?: PageBuilder;
  title_en?: string;
  slug_en?: Slug;
  content_en?: PageBuilder;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imageCredit_no?: string;
  imageCredit_en?: string;
  imageAlt_no?: string;
  imageAlt_en?: string;
  publishingStatus?: "published" | "draft" | "scheduled";
  scheduledPeriod?: {
    startDate?: string;
    endDate?: string;
  };
  seo?: Seo;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eventDate?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "eventDate";
  };
  eventTime?: {
    startTime?: "06:00" | "06:15" | "06:30" | "06:45" | "07:00" | "07:15" | "07:30" | "07:45" | "08:00" | "08:15" | "08:30" | "08:45" | "09:00" | "09:15" | "09:30" | "09:45" | "10:00" | "10:15" | "10:30" | "10:45" | "11:00" | "11:15" | "11:30" | "11:45" | "12:00" | "12:15" | "12:30" | "12:45" | "13:00" | "13:15" | "13:30" | "13:45" | "14:00" | "14:15" | "14:30" | "14:45" | "15:00" | "15:15" | "15:30" | "15:45" | "16:00" | "16:15" | "16:30" | "16:45" | "17:00" | "17:15" | "17:30" | "17:45" | "18:00" | "18:15" | "18:30" | "18:45" | "19:00" | "19:15" | "19:30" | "19:45" | "20:00" | "20:15" | "20:30" | "20:45" | "21:00" | "21:15" | "21:30" | "21:45" | "22:00" | "22:15" | "22:30" | "22:45" | "23:00" | "23:15" | "23:30" | "23:45";
    endTime?: "06:00" | "06:15" | "06:30" | "06:45" | "07:00" | "07:15" | "07:30" | "07:45" | "08:00" | "08:15" | "08:30" | "08:45" | "09:00" | "09:15" | "09:30" | "09:45" | "10:00" | "10:15" | "10:30" | "10:45" | "11:00" | "11:15" | "11:30" | "11:45" | "12:00" | "12:15" | "12:30" | "12:45" | "13:00" | "13:15" | "13:30" | "13:45" | "14:00" | "14:15" | "14:30" | "14:45" | "15:00" | "15:15" | "15:30" | "15:45" | "16:00" | "16:15" | "16:30" | "16:45" | "17:00" | "17:15" | "17:30" | "17:45" | "18:00" | "18:15" | "18:30" | "18:45" | "19:00" | "19:15" | "19:30" | "19:45" | "20:00" | "20:15" | "20:30" | "20:45" | "21:00" | "21:15" | "21:30" | "21:45" | "22:00" | "22:15" | "22:30" | "22:45" | "23:00" | "23:15" | "23:30" | "23:45";
  };
  eventDateValue?: string;
  venue?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "venue";
  };
  artist?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "artist";
  }>;
  composers?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "composer";
  }>;
  spotifyItems?: Array<{
    _key: string;
  } & SpotifyComponent>;
  ticketType?: "button" | "info";
  ticketUrl?: string;
  ticketInfoText?: string;
  ticketStatus?: "available" | "low_stock" | "sold_out";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imageCredit_no?: string;
  imageCredit_en?: string;
  imageAlt_no?: string;
  imageAlt_en?: string;
  title_no?: string;
  slug_no?: Slug;
  excerpt_no?: string;
  description_no?: PortableText;
  extraContent_no?: PageBuilder;
  title_en?: string;
  slug_en?: Slug;
  excerpt_en?: string;
  description_en?: PortableText;
  extraContent_en?: PageBuilder;
  publishingStatus?: "published" | "draft" | "scheduled";
  scheduledPeriod?: {
    startDate?: string;
    endDate?: string;
  };
  seo?: Seo;
};

export type Artist = {
  _id: string;
  _type: "artist";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  cardSize?: "stor" | "medium";
  excerpt_no?: string;
  instrument_no?: string;
  content_no?: PageBuilder;
  excerpt_en?: string;
  instrument_en?: string;
  content_en?: PageBuilder;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imageCredit_no?: string;
  imageCredit_en?: string;
  imageAlt_no?: string;
  imageAlt_en?: string;
  publishingStatus?: "published" | "draft" | "scheduled";
  scheduledPeriod?: {
    startDate?: string;
    endDate?: string;
  };
  events?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "event";
  }>;
  seo?: Seo;
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title_no?: string;
  slug_no?: Slug;
  excerpt_no?: string;
  content_no?: PageBuilder;
  title_en?: string;
  slug_en?: Slug;
  excerpt_en?: string;
  content_en?: PageBuilder;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imageCredit_no?: string;
  imageCredit_en?: string;
  imageAlt_no?: string;
  imageAlt_en?: string;
  publishingStatus?: "published" | "draft" | "scheduled";
  scheduledPeriod?: {
    startDate?: string;
    endDate?: string;
  };
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  indexingStatus?: "index" | "noindex";
};

export type Venue = {
  _id: string;
  _type: "venue";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  address?: string;
  linkUrl?: string;
  linkTarget?: "_self" | "_blank";
};

export type EventDate = {
  _id: string;
  _type: "eventDate";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  date?: string;
  title_display_no?: string;
  slug_no?: Slug;
  title_display_en?: string;
  slug_en?: Slug;
  isActive?: boolean;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = ComposerScrollContainer | EventScrollContainer | ArtistScrollContainer | ContentScrollContainer | ThreeColumnLayout | TwoColumnLayout | GridComponent | PageBuilder | CountdownComponent | AccordionComponent | LinkComponent | ButtonComponent | SpotifyComponent | VideoComponent | ImageComponent | PortableTextBlock | PortableText | HeadingComponent | MarqueeComponent | QuoteComponent | Title | SiteSettings | Composer | Homepage | ProgramPage | ArtistPage | ArticlePage | Page | Event | Artist | Article | Seo | Venue | EventDate | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/pages/api/countdown.ts
// Variable: EVENT_COUNTDOWN_QUERY
// Query: *[_type == "event" && _id == $eventId][0]{  eventDate->{date},  eventTime}
export type EVENT_COUNTDOWN_QUERYResult = {
  eventDate: {
    date: string | null;
  } | null;
  eventTime: {
    startTime?: "06:00" | "06:15" | "06:30" | "06:45" | "07:00" | "07:15" | "07:30" | "07:45" | "08:00" | "08:15" | "08:30" | "08:45" | "09:00" | "09:15" | "09:30" | "09:45" | "10:00" | "10:15" | "10:30" | "10:45" | "11:00" | "11:15" | "11:30" | "11:45" | "12:00" | "12:15" | "12:30" | "12:45" | "13:00" | "13:15" | "13:30" | "13:45" | "14:00" | "14:15" | "14:30" | "14:45" | "15:00" | "15:15" | "15:30" | "15:45" | "16:00" | "16:15" | "16:30" | "16:45" | "17:00" | "17:15" | "17:30" | "17:45" | "18:00" | "18:15" | "18:30" | "18:45" | "19:00" | "19:15" | "19:30" | "19:45" | "20:00" | "20:15" | "20:30" | "20:45" | "21:00" | "21:15" | "21:30" | "21:45" | "22:00" | "22:15" | "22:30" | "22:45" | "23:00" | "23:15" | "23:30" | "23:45";
    endTime?: "06:00" | "06:15" | "06:30" | "06:45" | "07:00" | "07:15" | "07:30" | "07:45" | "08:00" | "08:15" | "08:30" | "08:45" | "09:00" | "09:15" | "09:30" | "09:45" | "10:00" | "10:15" | "10:30" | "10:45" | "11:00" | "11:15" | "11:30" | "11:45" | "12:00" | "12:15" | "12:30" | "12:45" | "13:00" | "13:15" | "13:30" | "13:45" | "14:00" | "14:15" | "14:30" | "14:45" | "15:00" | "15:15" | "15:30" | "15:45" | "16:00" | "16:15" | "16:30" | "16:45" | "17:00" | "17:15" | "17:30" | "17:45" | "18:00" | "18:15" | "18:30" | "18:45" | "19:00" | "19:15" | "19:30" | "19:45" | "20:00" | "20:15" | "20:30" | "20:45" | "21:00" | "21:15" | "21:30" | "21:45" | "22:00" | "22:15" | "22:30" | "22:45" | "23:00" | "23:15" | "23:30" | "23:45";
  } | null;
} | null;

// Source: ./src/pages/api/filter-events.ts
// Variable: FILTER_EVENTS_QUERY
// Query: *[      _type == "event"      && publishingStatus == "published"      && (!defined($eventDate) || eventDate->date == $eventDate)      && (!defined($genre) || genre->slug.current == $genre)      && (!defined($venue) || venue->slug.current == $venue)    ] | order(eventDate->date asc, eventTime.startTime asc){      _id,      title_no,      title_en,      "title": coalesce(title_no, title_en, title),      "slug": coalesce(slug_no.current, slug_en.current, slug.current),      "image": {        "image": image,        "alt": coalesce(imageAlt_no, imageAlt_en, image.alt)      },      eventTime,      eventDate->{        date,        title_display_no,        title_display_en,        "title": coalesce(title_display_no, title_display_en)      },      venue->{title},      genre->{title},      "artists": artist[]->{name},      ticketType,      ticketUrl,      ticketInfoText,      ticketStatus    }
export type FILTER_EVENTS_QUERYResult = Array<{
  _id: string;
  title_no: string | null;
  title_en: string | null;
  title: string | null;
  slug: string | null;
  image: {
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    alt: string | null;
  };
  eventTime: {
    startTime?: "06:00" | "06:15" | "06:30" | "06:45" | "07:00" | "07:15" | "07:30" | "07:45" | "08:00" | "08:15" | "08:30" | "08:45" | "09:00" | "09:15" | "09:30" | "09:45" | "10:00" | "10:15" | "10:30" | "10:45" | "11:00" | "11:15" | "11:30" | "11:45" | "12:00" | "12:15" | "12:30" | "12:45" | "13:00" | "13:15" | "13:30" | "13:45" | "14:00" | "14:15" | "14:30" | "14:45" | "15:00" | "15:15" | "15:30" | "15:45" | "16:00" | "16:15" | "16:30" | "16:45" | "17:00" | "17:15" | "17:30" | "17:45" | "18:00" | "18:15" | "18:30" | "18:45" | "19:00" | "19:15" | "19:30" | "19:45" | "20:00" | "20:15" | "20:30" | "20:45" | "21:00" | "21:15" | "21:30" | "21:45" | "22:00" | "22:15" | "22:30" | "22:45" | "23:00" | "23:15" | "23:30" | "23:45";
    endTime?: "06:00" | "06:15" | "06:30" | "06:45" | "07:00" | "07:15" | "07:30" | "07:45" | "08:00" | "08:15" | "08:30" | "08:45" | "09:00" | "09:15" | "09:30" | "09:45" | "10:00" | "10:15" | "10:30" | "10:45" | "11:00" | "11:15" | "11:30" | "11:45" | "12:00" | "12:15" | "12:30" | "12:45" | "13:00" | "13:15" | "13:30" | "13:45" | "14:00" | "14:15" | "14:30" | "14:45" | "15:00" | "15:15" | "15:30" | "15:45" | "16:00" | "16:15" | "16:30" | "16:45" | "17:00" | "17:15" | "17:30" | "17:45" | "18:00" | "18:15" | "18:30" | "18:45" | "19:00" | "19:15" | "19:30" | "19:45" | "20:00" | "20:15" | "20:30" | "20:45" | "21:00" | "21:15" | "21:30" | "21:45" | "22:00" | "22:15" | "22:30" | "22:45" | "23:00" | "23:15" | "23:30" | "23:45";
  } | null;
  eventDate: {
    date: string | null;
    title_display_no: string | null;
    title_display_en: string | null;
    title: string | null;
  } | null;
  venue: {
    title: string | null;
  } | null;
  genre: null;
  artists: Array<{
    name: string | null;
  }> | null;
  ticketType: "button" | "info" | null;
  ticketUrl: string | null;
  ticketInfoText: string | null;
  ticketStatus: "available" | "low_stock" | "sold_out" | null;
}>;

// Source: ./src/pages/api/health.ts
// Variable: HEALTH_CHECK_QUERY
// Query: *[_type == "siteSettings"][0]{  _id,  _type}
export type HEALTH_CHECK_QUERYResult = {
  _id: string;
  _type: "siteSettings";
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"event\" && _id == $eventId][0]{\n  eventDate->{date},\n  eventTime\n}": EVENT_COUNTDOWN_QUERYResult;
    "*[\n      _type == \"event\"\n      && publishingStatus == \"published\"\n      && (!defined($eventDate) || eventDate->date == $eventDate)\n      && (!defined($genre) || genre->slug.current == $genre)\n      && (!defined($venue) || venue->slug.current == $venue)\n    ] | order(eventDate->date asc, eventTime.startTime asc){\n      _id,\n      title_no,\n      title_en,\n      \"title\": coalesce(title_no, title_en, title),\n      \"slug\": coalesce(slug_no.current, slug_en.current, slug.current),\n      \"image\": {\n        \"image\": image,\n        \"alt\": coalesce(imageAlt_no, imageAlt_en, image.alt)\n      },\n      eventTime,\n      eventDate->{\n        date,\n        title_display_no,\n        title_display_en,\n        \"title\": coalesce(title_display_no, title_display_en)\n      },\n      venue->{title},\n      genre->{title},\n      \"artists\": artist[]->{name},\n      ticketType,\n      ticketUrl,\n      ticketInfoText,\n      ticketStatus\n    }": FILTER_EVENTS_QUERYResult;
    "*[_type == \"siteSettings\"][0]{\n  _id,\n  _type\n}": HEALTH_CHECK_QUERYResult;
  }
}
